#:kivy 2.0.0

<IconButton@Button>:
    Image:
        source: root.icon
        x: root.x
        y: root.y
        size: (48, 48)

<TestRootWidget>:
    id: trw
    popup: popup.__self__
    orientation: 'vertical'

    canvas.before:
        Color:
            rgb: .6, .6, .6
        Rectangle:
            size: self.size
            source: 'cave/data/images/burdick.png'

    Popup:
        size_hint: (None, None)
        size: (300, 200)
        id: popup
        title: "Please wait"
        on_parent:
            if self.parent == trw: self.parent.remove_widget(self)
        Label:
            id: popup_label
            text: 'Please wait while the device powers on.'
            on_touch_down: popup.dismiss()

    ActionBar:
        ActionView:
            id: av
            ActionPrevious:
                title: app.current_tab_name
                on_release: app.go_tab(0)

            ActionSeparator:

            ActionButton:
                text: 'On'
                icon: 'cave/data/images/power-on.png'
                size_hint_x: .09

            ActionSeparator:

            ActionButton:
                text: 'Off'
                icon: 'cave/data/images/power-off.png'
                size_hint_x: .09

    SwipeAccordion:
        id: acc
        orientation: 'horizontal'
