#:kivy 2.0.0

<InputButton@Button>:
    Image:
        source: root.icon
        x: root.x
        y: root.y
        size: (48, 48)

<StatusBar@BoxLayout>:
    canvas.before:
        Color:
            rgb: 0.3, 0.3, 0.3
        Rectangle:
            size: self.size

<TestRootWidget>:
    id: trw
    popup: popup.__self__
    orientation: 'vertical'

    canvas.before:
        Color:
            rgb: .6, .6, .6
        Rectangle:
            size: self.size
            source: 'cave/data/images/burdick.png'

    Popup:
        size_hint: (None, None)
        size: (300, 200)
        id: popup
        title: "Please wait"
        on_parent:
            if self.parent == trw: self.parent.remove_widget(self)
        Label:
            id: popup_label
            text: 'Please wait while the device powers on.'
            on_touch_down: popup.dismiss()

    ActionBar:
        ActionView:
            id: av
            ActionPrevious:
                title: app.location + ' - ' + app.current_tab_title
                on_release: app.go_tab(list(app.available_tabs.keys())[0])

            ActionSeparator:

            ActionButton:
                text: 'On'
                icon: 'cave/data/images/power-on.png'
                size_hint_x: .09
                on_press:
                    sai.start();\
                    app.status = 'Making it so...'

            ActionSeparator:

            ActionButton:
                text: 'Off'
                icon: 'cave/data/images/power-off.png'
                size_hint_x: .09
                on_press:
                    sai.stop();\
                    app.status = ''

    SwipeAccordion:
        id: acc
        orientation: 'horizontal'

#        SwipeAccordionItem:
#            id: accordion_tab_0
#            title: 'Home'
#
#            FloatLayout:
#
#                Label:
#                    text: 'Home'
#                    pos_hint_x: .09
#                    pos_hint_y: .5
#                    font_size: '20dp'
#                    size_hint_x: .8
#                    size_hint_y: .6
#
#                GridLayout:
#                    cols: 4
#                    spacing: '20dp'
#                    size_hint_x: .8
#                    size_hint_y: None
#                    pos_hint_x: .1
#                    pos_hint_y: .5
#
#                    InputButton:
#                        size_hint_y: None
#                        height: '48dp'
#                        text: 'Computer'
#                        _device_id: 'test_projector'
#                        _input: 'RGB_1'
#                        Image:
#                            source: 'cave/data/images/computer.png'
#                            x: root.x
#                            y: root.y
#                            size: (48, 48)
#
#                    InputButton:
#                        size_hint_y: None
#                        height: '48dp'
#                        text: 'HDMI'
#                        _device_id: 'test_projector'
#                        _input: 'HDMI_1'
#                        Image:
#                            source: 'cave/data/images/blank.png'
#                            x: root.x
#                            y: root.y
#                            size: (48, 48)
#
#                    InputButton:
#                        size_hint_y: None
#                        height: '48dp'
#                        text: 'Video (composite)'
#                        _device_id: 'test_projector'
#                        _input: 'VIDEO_1'
#                        Image:
#                            source: 'cave/data/images/blank.png'
#                            x: root.x
#                            y: root.y
#                            size: (48, 48)



    StatusBar:
        orientation: 'vertical'
        size_hint_y: .12

        Label:
            text: app.status
        StatusActivityIndicator:
            id: sai
            time: app.time
            value: 0
